"""Filter and Deduplication Module (Root Compatibility Facade)."""
from __future__ import annotations

from job_radar.filters.dedupe import (
    SEEN_MAX_AGE,
    _load_seen,
    _save_seen,
    dedupe,
    dedupe_junior_ai,
    dedupe_junior_ai_multi,
    dedupe_radar_jobs,
    extract_canonical_job_url,
    extract_job_key,
    job_fingerprint,
    normalize_company_name,
    normalize_job_location,
    normalize_job_title,
)
from job_radar.filters.matching import (
    AI_EARLY_CAREER_INCLUDE,
    AI_INTERNSHIP_INCLUDE,
    ENGINEER_LEVEL_INCLUDE,
    INTERNSHIP_TERMS,
    KEYWORDS_EXCLUDE,
    KEYWORDS_EXCLUDE_COMPILED,
    KEYWORDS_INCLUDE,
    KEYWORDS_INCLUDE_COMPILED,
    SENIORITY_EXCLUDE,
    SENIORITY_EXCLUDE_COMPILED,
    has_visa_signal,
    is_matching_role,
    is_senior_role,
    match_track,
    matches,
    matches_junior_ai,
)

__all__ = [
    "KEYWORDS_INCLUDE",
    "KEYWORDS_EXCLUDE",
    "KEYWORDS_INCLUDE_COMPILED",
    "KEYWORDS_EXCLUDE_COMPILED",
    "INTERNSHIP_TERMS",
    "ENGINEER_LEVEL_INCLUDE",
    "SENIORITY_EXCLUDE",
    "SENIORITY_EXCLUDE_COMPILED",
    "AI_INTERNSHIP_INCLUDE",
    "AI_EARLY_CAREER_INCLUDE",
    "is_matching_role",
    "is_senior_role",
    "match_track",
    "matches",
    "matches_junior_ai",
    "has_visa_signal",
    "extract_job_key",
    "extract_canonical_job_url",
    "normalize_company_name",
    "normalize_job_title",
    "normalize_job_location",
    "job_fingerprint",
    "SEEN_MAX_AGE",
    "_load_seen",
    "_save_seen",
    "dedupe",
    "dedupe_radar_jobs",
    "dedupe_junior_ai_multi",
    "dedupe_junior_ai",
]
