"""Errors module public API."""
from .base import (
    VisaLaneError,
    AuthenticationError,
    AuthorizationError,
    ValidationError,
    FileSizeError,
    FileTypeError,
    ContentError,
    NotFoundError,
    JobNotFoundError,
    ResumeNotFoundError,
    UsageLimitError,
    GenerationError,
    HallucinationError,
    ResumeParseError,
    ScannedPdfError,
    EncryptedFileError,
    ExternalServiceError,
    EmailDeliveryError,
    DatabaseError,
    from_exception,
)

__all__ = [
    "VisaLaneError",
    "AuthenticationError",
    "AuthorizationError",
    "ValidationError",
    "FileSizeError",
    "FileTypeError",
    "ContentError",
    "NotFoundError",
    "JobNotFoundError",
    "ResumeNotFoundError",
    "UsageLimitError",
    "GenerationError",
    "HallucinationError",
    "ResumeParseError",
    "ScannedPdfError",
    "EncryptedFileError",
    "ExternalServiceError",
    "EmailDeliveryError",
    "DatabaseError",
    "from_exception",
]
